### PR TITLE
Fix tests 

### PR DESCRIPTION
**Pull request by byterussian**

### CODE REVIEW

**Comment by byterussian** [comment]
@mnoack This pull request optimize a bit the test workflow by removing the useless gems and activating the Travis CI cache for bundler. It may be useful to limit the timeout errors.

**Comment by mnoack** [comment]
Excellent @byterussian we've been suffering with failing tests since 2.2 testing was added.

**Comment by byterussian** [comment]
Oh, finally the green badge :smile:. Great.

PS: take a look at the coveralls integration @mnoack . Seems broken.

**Comment by mnoack** [comment]
Looks like coveralls never was finished, now I've fixed that, unfortunately it's poor, but then again, when I took over geokit/geokit-rails the tests were far from passing and didn't measure coverage :)

**Pull request merged**
