### PR TITLE
Initializer generator.

### LINKED ISSUE #51: Where is config file?
The README refers to file assets/api_keys_template for a default configuration file.  This seems to be missing.  I see no source for the configuration file anywhere in the source.  I was expecting a rake task or some such to generate the default configuration file.

### PR DESCRIPTION
**Pull request by byterussian**
Resolve #51

### CODE REVIEW

**Comment by alotofnoodles** [comment]
:+1:

**Comment by mnoack** [comment]
If you rebase this from master to avoid merge conflicts I'm happy to merge as I know the build is failing due to other reasons.

**Comment by byterussian** [comment]
@mnoack Done

**Comment by mnoack** [comment]
Thanks @byterussian

**Pull request merged**
